# Generated by Django 4.1.4 on 2022-12-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_services_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expired_payments',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Penalty_fee_amount', models.FloatField(default=0.0)),
                ('Payment_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.payment_user')),
            ],
        ),
    ]
